export const configurationInformation =
{
    "name": "Ninja-Se 5x4",
    "Configuration": {
        "numColumns": "4",
        "numRows": "5",
        "level" : "1",
    },
    "Ninja" : [
        {
        "inventory" : false,
        "row" : 2,
        "column" : 0,
        }
    ],

    "cells" : [
    {   
        "row" : "0",
        "column" : "0",
        "wall" : false,
        "key" : false,
              
    },
    {   "row" : "0",
        "column" : "1",
        "wall" : false,
        "key" : false,  
    },
    {   "row" : "0",
        "column" : "2",
        "wall" : false,
        "key" : true,  
    },
    {   "row" : "0",
        "column" : "3",
        "wall" : true,
        "key" : false,
        "door" : false,  

    },
    {   "row" : "1",
        "column" : "0",
        "wall" : false,
        "key" : false,  
    },
    {   "row" : "1",
        "column" : "1",
        "wall" : true,
        "key" : false,  
    },
    {   "row" : "1",
        "column" : "2",
        "wall" : true,
        "key" : false,  
    },
    {   "row" : "1",
        "column" : "3",
        "wall" : true,
        "key" : false,  
    },
    {   "row" : "2",
        "column" : "0",
        "wall" : false,
        "key" : false,  
    },
    {   "row" : "2",
        "column" : "1",
        "wall" : false,
        "key" : false,  
    },
    {   "row" : "2",
        "column" : "2",
        "wall" : false,
        "key" : false,  
    },
    {   "row" : "2",
        "column" : "3",
        "wall" : true,
        "key" : false,
        "door" : true,  
    },
    {   "row" : "3",
        "column" : "0",
        "wall" : true,
        "key" : false,  
    },
    {   "row" : "3",
        "column" : "1",
        "wall" : true,
        "key" : false,  
    },
    {   "row" : "3",
        "column" : "2",
        "wall" : false,
        "key" : false,  
    },
    {   "row" : "3",
        "column" : "3",
        "wall" : true,
        "key" : false,  
    },
    {   "row" : "4",
        "column" : "0",
        "wall" : false,
        "key" : true,  
    },
    {   "row" : "4",
        "column" : "1",
        "wall" : true,
        "key" : false,
        "door" : true,
    },
    {   "row" : "4",
        "column" : "2",
        "wall" : false,
        "key" : false,  
    },
    {   "row" : "4",
        "column" : "3",
        "wall" : true,
        "key" : false,  
    },
    ],

    "walls" : [
        { "row":0, "column":3},
        { "row":1, "column":1},
        { "row":1, "column":2},
        { "row":1, "column":3},
        { "row":3, "column":0},
        { "row":3, "column":1},
        { "row":3, "column":3},
        { "row":4, "column":3},
      ],

    "keys" : [
    {
        "row" : "0",
        "column" : "2",
        "color" : "red"
    },
    {
        "row" : "4",
        "column" : "0",
        "color" : "green",

    }
    ],

    "doors" : [
    {
        "row" : "2",
        "column" : "3",
        "color" : "green",
    },
    {
        "row" : "4",
        "column" : "1",
        "color" : "red",
    },
    ],
};



export const configurationInformation2 =
{
    "name": "Ninja-Se 3x4",
    "Configuration": {
        "numColumns": "4",
        "numRows": "3",
        "level" : "2",
    },
    "Ninja" : [
        {
        "inventory" : false,
        "row" : 1,
        "column" : 0,
        }
    ],
    "cells" : [
    {   
        "row" : "0",
        "column" : "0",
        "wall" : true,
        "key" : false,
              
    },
    {   "row" : "0",
        "column" : "1",
        "wall" : true,
        "key" : false,  
    },
    {   "row" : "0",
        "column" : "2",
        "wall" : false,
        "key" : false,  
    },
    {   "row" : "0",
        "column" : "3",
        "wall" : false,
        "key" : true,  

    },
    {   "row" : "1",
        "column" : "0",
        "wall" : false,
        "key" : false,  
    },
    {   "row" : "1",
        "column" : "1",
        "wall" : false,
        "key" : true,  
    },
    {   "row" : "1",
        "column" : "2",
        "wall" : false,
        "key" : true,  
    },
    {   "row" : "1",
        "column" : "3",
        "wall" : true,
        "key" : false,  
    },
    {   "row" : "2",
        "column" : "0",
        "wall" : true,
        "key" : false,  
    },
    {   "row" : "2",
        "column" : "1",
        "wall" : true,
        "key" : false,  
    },
    {   "row" : "2",
        "column" : "2",
        "wall" : false,
        "key" : true,  
    },
    {   "row" : "2",
        "column" : "3",
        "wall" : false,
        "key" : true,  
    },
    ],

    "walls" : [],

    "keys" : [
    {
        "row" : "0",
        "column" : "3",
        "color" : 'blue',
    },
    {
        "row" : "1",
        "column" : "1",
        "color" : "red",
    },
    {
        "row" : "1",
        "column" : "2",
        "color" : "green",
    },
    {
        "row" : "2",
        "column" : "2",
        "color" : "red",
    },
    {
        "row" : "2",
        "column" : "3",
        "color" : "green",
    },
    ],

    "doors" : [
        {
            "row" : "0",
            "column" : "0",
            "color" : "red",
        },
        {
            "row" : "0",
            "column" : "1",
            "color" : "blue",
        },
        {
            "row" : "1",
            "column" : "3",
            "color" : "green",
        },
        {
            "row" : "2",
            "column" : "0",
            "color" : "green", 
        },
        {
            "row" : "2",
            "column" : "1",
            "color" : "red",
        },
        ],
};



export const configurationInformation3 =
{
    "name": "Ninja-Se 5x4",
    "Configuration": {
        "numColumns": "5",
        "numRows": "2",
        "level" : "3",
    },
    "Ninja" : [
        {"inventory" : false,
        "row" : 0,
        "column" : 0,},
    ],

    "cells" : [
    {   
        "row" : "0",
        "column" : "0",
        "wall" : false,
        "key" : false,
              
    },
    {   "row" : "0",
        "column" : "1",
        "wall" : false,
        "key" : true,  
    },
    {   "row" : "0",
        "column" : "2",
        "wall" : false,
        "key" : true,  
    },
    {   "row" : "0",
        "column" : "3",
        "wall" : false,
        "key" : true,  

    },
    {   "row" : "0",
        "column" : "4",
        "wall" : true,
        "key" : false,  
    },
    {   "row" : "1",
        "column" : "0",
        "wall" : true,
        "key" : false,  
    },
    {   "row" : "1",
        "column" : "1",
        "wall" : true,
        "key" : false,  
    },
    {   "row" : "1",
        "column" : "2",
        "wall" : true,
        "key" : false,  
    },
    {   "row" : "1",
        "column" : "3",
        "wall" : true,
        "key" : false,  
    },
    {   "row" : "1",
        "column" : "4",
        "wall" : false,
        "key" : true,  
    },
    ],

    "walls" : [ { "row":1, "column":0 } ],

    "keys" : [
        {
            "row" : "0",
            "column" : "1",
            "color" : 'red',
        },
        {
            "row" : "0",
            "column" : "2",
            "color" : "green",
        },
        {
            "row" : "0",
            "column" : "3",
            "color" : "blue",
        },
        {
            "row" : "1",
            "column" : "4",
            "color" : "yellow",
        },
    ],
    
    
    "doors" : [
        {
            "row" : "0",
            "column" : "4",
            "color" : "red",
        },
        {
            "row" : "1",
            "column" : "1",
            "color" : "yellow",
        },
        {
            "row" : "1",
            "column" : "2",
            "color" : "blue",
        },
        {
            "row" : "1",
            "column" : "3",
            "color" : "green", 
        },
        ],

};